ch99/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
  # example: /blog/
  path('', views.PostLV.as_view(), name='index'),

  # example: /blog/post/ (same as /blog/)
  path('post/', views.PostLV.as_view(), name='post_list'),

  # example: /blog/post/django-example/
  re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
  # slug를 사용할 땐, 한글은 인식을 못하고, re_path를 사용해서 정규 표현식을 써야만 한글
  # path('post/<slug:slug>/', views.PostDV.as_view(), name='post_detail'),

  # example: /blog/archive/
  path('archive/', views.PostAV.as_view(), name='post_archive'),

  # example: /blog/archive/2019
  path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

  # example: /blog/archive/2019/nov/
  path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

  # example: /blog/archive/2019/nov/10/
  path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

  # example: /blog/archive/today/
  path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
]

ch99/bookmark/urls.py
from django.urls import path
from .views import BookmarkLV, BookmarkDV

app_name = 'bookmark'
urlpatterns = [
  path('', BookmarkLV.as_view(), name='index'),
  path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

ch99/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
]

ch99/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
  title = models.CharField(verbose_name="TITLE", max_length=50)
  slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
  description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
  content = models.TextField('CONTENT')
  create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
  modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

  class Meta:
    verbose_name = 'post'
    verbose_name_plural = 'posts'
    db_table = 'blog_posts'
    ordering = ('-modify_dt',)

  def __str__(self):
    return self.title
  
  # def get_absolute_url(self):
  #     return reverse("model_detail", kwargs={"pk": self.pk})
  
  def get_absolute_url(self):
    # print('🥇',self.slug)
    return reverse("blog:post_detail", kwargs={'slug': self.slug}) #args=(self.slug,)
  
  def get_previous(self):
    return self.get_previous_by_modify_dt()

  def get_next(self):
    return self.get_next_by_modify_dt()
  

ch99/bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model):
  title = models.CharField('TITLE', max_length=100, blank=True)
  url = models.URLField('URL', unique=True)

  def __str__(self):
    return '%s %s' %(self.title, self.url)

ch99/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView

from .models import Post
# Create your views here.

# ListView -> object_list
class PostLV(ListView):
  model = Post
  template_name = 'blog/post_all.html'
  context_object_name = 'posts'
  paginate_by = 2

# DetailView -> object
class PostDV(DetailView):
  model = Post

# ArchiveIndexView -> object_list, latest
class PostAV(ArchiveIndexView):
  model = Post
  date_field = 'modify_dt'

# object_list
class PostYAV(YearArchiveView):
  model = Post
  date_field = 'modify_dt'
  make_object_list = True

# object_list
class PostMAV(MonthArchiveView):
  model = Post
  date_field = 'modify_dt'

# object_list
class PostDAV(DayArchiveView):
  model = Post
  date_field = 'modify_dt'

# object_list
class PostTAV(TodayArchiveView):
  model = Post
  date_field = 'modify_dt'
  

ch99/bookmark/views.py
from django.shortcuts import render
from .models import Bookmark
from django.views.generic import ListView, DetailView

# Create your views here.
class BookmarkLV(ListView):
  model = Bookmark

class BookmarkDV(DetailView):
  model = Bookmark

ch99/blog/templates/blog/post_all.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Post All</title>
  </head>
  <body>
    <h1>Blog List</h1>
    <br />
    {% for post in posts %}
    <h3><a href="{{post.get_absolute_url}}"> {{post.title}} </a></h3>
    {{post.modify_dt|date:'N d, Y'}}
    <p>{{post.description}}</p>
    {% endfor %}
    <br />
    <div>
      <span>
        {% if page_obj.has_previous %}
        <a href="?page={{page_obj.previous_page_number}}">PreviousPage</a>
        {% endif %} Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} {% if page_obj.has_next %}
        <a href="?page={{page_obj.next_page_number}}">NextPage</a>
        {% endif %}
      </span>
    </div>
  </body>
</html>

ch99/blog/templates/blog/post_archive.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Post Archive until {% now 'N d, Y' %}</h1>
    <ul>
      {% for date in date_list %}
      <li style="display: inline">
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year{{date|date:'Y'}}</a>
      </li>
      {% endfor%}
    </ul>
    <br />
    <div>
      <ul>
        {% for post in object_list %}
        <li>
          {{post.modify_dt|date:'Y-m-d'}}&nbsp;&nbsp;&nbsp;
          <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>

ch99/blog/templates/blog/post_archive_day.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Post Archives for {{day|date:'N d, Y'}}</h1>
    <div>
      <ul>
        {% for post in object_list %}
        <li>
          {{post.modify_dt|date:'Y-m-d'}}&nbsp;&nbsp;&nbsp;
          <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>

ch99/blog/templates/blog/post_archive_month.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Post Archives for {{month|date:'N, Y'}}</h1>
    <div>
      <ul>
        {% for post in object_list %}
        <li>
          {{post.modify_dt|date:'Y-m-d'}}&nbsp;&nbsp;&nbsp;
          <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>

ch99/blog/templates/blog/post_archive_year.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Post Archives for {{year|date:'Y'}}</h1>
    <ul>
      {% for date in date_list %}
      <li>
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{date|date:'F'}}</a>
      </li>
      {% endfor %}
    </ul>
    <br />
    <div>
      <ul>
        {% for post in object_list %}
        <li>
          {{post.modify_dt|date:'Y-m-d'}}&nbsp;&nbsp;&nbsp;
          <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>

ch99/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h2>{{object.title}}</h2>
    <p>
      {% if object.get_previous %}
      <a href="{{object.get_previous.get_absolute_url}}" title="View previous post"> &laquo;-- {{object.get_previous}} </a>
      {% endif %} {% if object.get_next %} |<a href="{{object.get_next.get_absolute_url}}" title="View next post">
        {{object.get_next}} --&raquo;
      </a>
      {% endif %}
    </p>
    <p>{{object.modify_dt|date:'j F Y'}}</p>
    <br />
    <div>{{object.content|linebreaks}}</div>
  </body>
</html>

ch99/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Bookmark Detail</title>
  </head>
  <body>
    <div id="content">
      <h1>{{object.title}}</h1>
      <ul>
        <li>URL: <a href="{{object.url}}">{{object.url}}</a></li>
      </ul>
    </div>
  </body>
</html>

ch99/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Bookmark List</title>
  </head>
  <body>
    <div id="content">
      <h1>Bookmark List</h1>
      <ul>
        {% for bookmark in object_list %}
        <li>
          <a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark.title}}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>