kkostagram/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("sign_up/", views.sign_up, name="sign_up"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

kkostagram/kkostagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kkostagram/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns=[
    path('', views.index, name='index'),
    path("<int:post_pk>/", views.detail, name='detail'),
    path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("<int:post_pk>/edit/", views.edit, name="edit"),
    path("<int:post_pk>/update", views.update, name="update"),
    path("<int:post_pk>/delete", views.delete, name="delete"),
    path("<int:post_pk>/like", views.like, name="like"),
]

kkostagram/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    # author = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    body = models.TextField()
    image = models.ImageField(upload_to="posts", null=True)
    created_at = models.DateTimeField()
    liked_users = models.ManyToManyField(User, related_name="liked_posts")

    def __str__(self):
        # return f'{self.author}: {self.body}'
        if self.user:
            return f"{self.user.get_username}: {self.body}"

        return f"{self.body}"

kkostagram/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def sign_up(request):
    context = {}
    if request.method == "POST":
        if (request.POST["username"] and request.POST["password"] and request.POST["password"] == request.POST["password_check"]):
            new_user = User.objects.create_user(
                username = request.POST["username"],
                password = request.POST["password"],
            )
            auth.login(request, new_user)
            return redirect("posts:index")
        else:
            context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'

    return render(request, "accounts/sign_up.html", context)

def login(request):
    context = {}

    if request.method == "POST":
        if request.POST["username"] and request.POST["password"]:
            user = auth.authenticate(
                request,
                username = request.POST["username"],
                password = request.POST["password"]
            )
            if user is not None:
                auth.login(request, user)
                return redirect("posts:index")
            else:
                context["error"] = "아이디와 비밀번호를 다시 확인해주세요."
        else:
            context["error"] = "아이디와 비밀번호를 다시 확인해주세요."

    return render(request, "accounts/login.html", context)

def logout(request):
    if request.method == "POST":
        auth.logout(request)

    return redirect("posts:index")

kkostagram/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    posts = Post.objects.all()
    context = {
        "posts":posts
    }
    return render(request, 'posts/index.html', context)

def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    context = {
        "post": post
    }
    return render(request, "posts/detail.html", context)

@login_required
def new(request):
    return render(request, "posts/new.html")

@login_required
def create(request):
    user = request.user
    body = request.POST['body']

    image = None
    if "image" in request.FILES:
        image = request.FILES['image']

    post = Post(user= user, body= body, image= image, created_at= timezone.now())
    post.save()

    return redirect("posts:detail", post_pk= post.pk)

@login_required
def edit(request, post_pk):
    try:
        post = Post.objects.get(pk=post_pk, user=request.user)
    except Post.DoesNotExist:
        return redirect("posts:index")

    context = {
        "post":post
    }

    return render(request, "posts/edit.html", context)

@login_required
def update(request, post_pk):
    try:
        post = Post.objects.get(pk=post_pk, user=request.user)
    except Post.DoesNotExist:
        return redirect("posts:index")

    post.body = request.POST["body"]

    if "image" in request.FILES:
        post.image = request.FILES["image"]

    post.save()

    return redirect("posts:detail", post_pk=post.pk)

@login_required
def delete(request, post_pk):
    try:
        post = Post.objects.get(pk=post_pk, user=request.user)
    except Post.DoesNotExist:
        return redirect("posts:index")

    post.delete()

    return redirect("posts:index")

@login_required
def like(request, post_pk):
    if request.method == "POST":
        try:
            post = Post.objects.get(pk=post_pk)

            if request.user in post.liked_users.all():
                post.liked_users.remove(request.user)
            else:
                post.liked_users.add(request.user)

        except Post.DoesNotExist:
            pass

    return redirect("posts:index")

kkostagram/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}

    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <h1>Login</h1>

        <div class="form-group">
            <label for="username">아이디</label>
            <input type="text" id="username" name="username" placeholder="아이디" />
        </div>

        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" id="password" name="password" placeholder="비밀번호" />
        </div>

        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

kkostagram/accounts/templates/accounts/sign_up.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}

    <form action="{% url 'accounts:sign_up' %}" method="POST">
    {% csrf_token %}
        <h1>Sign Up</h1>

        <div class="form-group">
            <lable for="username">아이디</lable>
            <input type="text" id="username" name="username" placeholder="아이디" />
        </div>

        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" id="password" name="password" placeholder="비밀번호" />
        </div>

        <div class="form-group">
            <label for="password_check">비밀번호확인</label>
            <input type="password" id="password_check" name="password_check" placeholder="비밀번호확인">
        </div>

        <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
</div>
{% endblock %}

kkostagram/posts/templates/posts/detail.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
<div class="container">
    <h1>Post Detail</h1>

    {% if post.image %}
        <div>
            <img src="{{ post.image.url }}"></img>
        </div>
    {% endif %}
    <form>
        <div class="form-group">
            <label for="body">본문</label>
            <textarea readonly class="form-control-plaintext" name="body" id="body" cols="40" rows="10">{{ post.body }}</textarea>
        </div>

        <div>{{ post.created_at }}</div>
    </form>

    <div>
        좋아요 수 : {{ post.liked_users.count }}
    </div>

    {% if user.is_authenticated %}
        {% if user in post.liked_users.all %}
            <form action="{% url 'posts:like' post.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Like</button>
            </form>
        {% else %}
            <form action="{% url 'posts:like' post.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Like</button>
            </form>
        {% endif %}
    {% endif %}

    <a href="{% url 'posts:index' %}">목 록</a>

    {% if user == post.user %}
        <a href="{% url 'posts:edit' post.pk %}">수정하기</a>
        <a href="{% url 'posts:delete' post.pk %}">삭제하기</a>
    {% endif %}
</div>
{% endblock %}

kkostagram/posts/templates/posts/edit.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
<div class="container">
    <h1>Edit Post</h1>

    {% if post.image %}
        <div>
            <img src="{{ post.image.url }}"></img>
        </div>
    {% endif %}

    <form action="{% url 'posts:update' post.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="body">본문</label>
            <textarea class="form-control" cols=40 rows=10 id="body" name="body">{{ post.body }}</textarea>
        </div>

        <div>
            <label for="image">이미지</label>
            <input type="file" class="form-control-file" id="image" name="image">
        </div>

        <button type="submit" class="btn btn-primary">수정하기</button>
    </form>

    <a href="{% url 'posts:index' %}">목 록</a>
</div>
{% endblock %}

kkostagram/posts/templates/posts/index.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
<div class="container">
    <h1>Posts</h1>
    {% if posts %}
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>작 성 자</th>
                    <th>본 문</th>
                    <th>게 시 일</th>
                    <th>상 세</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <th>{{ post.pk }}</th>
                        <th>{{ post.user.get_username }}</th>
                        <th>{{ post.body }}</th>
                        <th>{{ post.created_at }}</th>
                        <th><a href="{% url 'posts:detail' post.pk %}">보 기</a></th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No Posts.</p>
    {% endif %}

    <a href="{% url 'posts:new' %}">글 쓰 기</a>
</div>
{% endblock %}

kkostagram/posts/templates/posts/new.html
{% extends "base.html" %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
<div class="container">
    <h1>New Post</h1>

    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="body">본문</label>
            <textarea class="form-control" cols=40 rows=10 id="body" name="body" placeholder="글을 작성해주세요."></textarea>
        </div>

        <div class="form-group">
            <label for="image">이미지</label>
            <input type="file" class="form-control-file" id="image" name="image" />
        </div>

        <button type="submit" class="btn btn-primary">작성하기</button>
    </form>
    <br/>
    <a href="{% url 'posts:index' %}">목 록</a>
</div>
{% endblock %}

kkostagram/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>KkoStagram</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    {% block style %}
    {% endblock %}

</head>
<body>
    {% if user.is_authenticated %}
        <div class="container">
            <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                {{ user.get_username }}님 환영합니다.
                <button type="submit" class="btn btn-primary">Logout</button>
            </form>
        </div>
    {% else %}
        <div class="container">
            <a href="{% url 'accounts:login' %}">
                <button type="button" class="btn btn-primary">Login</button>
            </a>

            <a href="{% url 'accounts:sign_up' %}">
                <button type="button" class="btn btn-primary">Sign_Up</button>
            </a>
        </div>
    {% endif %}

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>